In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/Michaeljo112/Estimando-la-pobreza-parroquial/main/datos22.xlsx"

df = pd.read_excel(url, sheet_name='data', index_col=None)

df.head()

,ADM3_PCODE,Año,viirs,pop,m2_auo,edi,crts,dt,ct,ds,...,ndvi,mndwi,area,icl,Provincia,Cantón,Parroquia,Personas,No pobres,Pobres
0,EC010155,2022,2.048737,6006,1.068972e+06,0,209,0.000529,11.0,0.131868,...,0.483085,-0.392392,9.345615e+07,inf,Azuay,Cuenca,Chiquintad,5738,3910,1828
1,EC010360,2022,2.771702,765,3.404005e+05,0,35,0.001965,1.0,0.000000,...,0.457337,-0.351759,1.193668e+07,inf,Azuay,Gualaceo,Simón Bolívar,732,349,383
2,EC010451,2022,0.999276,3118,2.974884e+06,0,154,0.000343,4.0,0.000000,...,0.432284,-0.366051,1.104506e+08,inf,Azuay,Nabón,Cochapata,2981,820,2161
3,EC010556,2022,1.476319,734,2.480622e+05,0,67,0.000887,2.0,0.000000,...,0.525941,-0.292900,3.610658e+07,inf,Azuay,Paute,Guarainag,701,389,312
4,EC011152,2022,2.999582,1960,4.415597e+05,0,41,0.001541,2.0,0.000000,...,0.509769,-0.303098,1.367559e+07,inf,Azuay,Chordeleg,La Unión,1875,928,947

In [2]:
df['Tasa de pobreza'] = df['Pobres']/df['Personas']

In [3]:
import numpy as np
df['almenoslamitadpobre'] = np.where(df['Tasa de pobreza'] >= .5, 1, 0)

In [4]:
espejo = df[df['Cantón'] == 'Espejo'][['Parroquia', 'almenoslamitadpobre']]
espejo

       Parroquia  almenoslamitadpobre
119     El Ángel                    0
138   San Isidro                    0
514   El Goaltal                    1
515  La Libertad                    0

In [5]:
espejo['almenoslamitadpobre'].sum()/4

np.float64(0.25)

In [6]:
resumenindicador = df.groupby(['Provincia', 'Cantón'])['almenoslamitadpobre'].mean().reset_index(name='indicador_pobreza')
resumenindicador.head()

  Provincia                 Cantón  indicador_pobreza
0     Azuay  Camilo Ponce Enríquez           0.000000
1     Azuay              Chordeleg           0.200000
2     Azuay                 Cuenca           0.272727
3     Azuay                 El Pan           0.000000
4     Azuay                  Girón           0.000000

In [7]:
resumenindicador.sort_values(by='indicador_pobreza', ascending=False)

      Provincia                    Cantón  indicador_pobreza
7         Azuay                     Nabón                1.0
10        Azuay                    Pucará                1.0
16      Bolívar                 Chillanes                1.0
20      Bolívar                 Las Naves                1.0
78       Guayas                    Balzar                1.0
..          ...                       ...                ...
190   Pichincha  San Miguel de los Bancos                0.0
204  Tungurahua       Baños de Agua Santa                0.0
211  Tungurahua                   Tisaleo                0.0
206  Tungurahua                     Mocha                0.0
205  Tungurahua                  Cevallos                0.0

[221 rows x 3 columns]